/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ffmpeg_CaptureCamera */

#ifndef _Included_com_ffmpeg_CaptureCamera
#define _Included_com_ffmpeg_CaptureCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ffmpeg_CaptureCamera
 * Method:    startCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ffmpeg_CaptureCamera_startCapture
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
