/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ffmpeg_HelloJni */

#ifndef _Included_com_ffmpeg_HelloJni
#define _Included_com_ffmpeg_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ffmpeg_HelloJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ffmpeg_HelloJni_sayHello
  (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_ffmpeg_HelloJni_sayHello1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
